# Generated by Django 4.2 on 2023-06-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstorage',
            name='notification_finish',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Письмо'),
        ),
    ]
